version: "3.9"

services:
  opensearch:
    image: opensearchproject/opensearch:latest
    environment:
      OPENSEARCH_INITIAL_ADMIN_PASSWORD: 1P@ssw0rd2
      discovery.type: single-node
      plugins.security.disabled: true # disable https and logins
      compatibility.override_main_response_version: true
    ports:
      - "9200:9200"
      - "9600:9600" # required for performance analyser
  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    ports:
      - "5601:5601"
    environment:
      OPENSEARCH_HOSTS: '["http://opensearch:9200"]'
      DISABLE_SECURITY_DASHBOARDS_PLUGIN: "true"
